# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siuntejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siuntejo_vardas', models.CharField(max_length=100)),
                ('siuntejo_pavarde', models.CharField(max_length=100)),
                ('pag_surinkimas_pirmadienis', models.BooleanField(default=False)),
                ('pag_surinkimas_antradienis', models.BooleanField(default=False)),
                ('pag_surinkimas_treciadienis', models.BooleanField(default=False)),
                ('pag_surinkimas_ketvirtadienis', models.BooleanField(default=False)),
                ('pag_surinkimas_penktadienis', models.BooleanField(default=False)),
                ('pag_surinkimas_sestadienis', models.BooleanField(default=False)),
                ('pag_surinkimas_sekmadienis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Siuntiniai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siuntinio_svoris', models.FloatField()),
                ('siuntinio_ilgis', models.IntegerField()),
                ('siuntinio_plotis', models.IntegerField()),
                ('siuntinio_apibudinimas', models.CharField(max_length=200)),
                ('siuntejas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagrindinis.Siuntejas')),
            ],
        ),
        migrations.CreateModel(
            name='Vezejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imones_pavadinimas', models.CharField(max_length=100, unique=True)),
                ('imones_kodas', models.CharField(max_length=100, unique=True)),
                ('imones_regsalis', models.CharField(max_length=100)),
                ('surinkimas_pirmadienis', models.BooleanField(default=False)),
                ('surinkimas_antradienis', models.BooleanField(default=False)),
                ('surinkimas_treciadienis', models.BooleanField(default=False)),
                ('surinkimas_ketvirtadienis', models.BooleanField(default=False)),
                ('surinkimas_penktadienis', models.BooleanField(default=False)),
                ('surinkimas_sestadienis', models.BooleanField(default=False)),
                ('surinkimas_sekmadienis', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='vezejas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagrindinis.Vezejas'),
        ),
    ]
