# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siuntejas',
            name='sukurimo_data',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 14, 20, 30, 555401, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='sukurimo_data',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 14, 20, 33, 517187, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vezejas',
            name='sukurimo_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
