# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0002_auto_20170517_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siuntiniai',
            name='siuntinio_ilgis',
        ),
        migrations.RemoveField(
            model_name='siuntiniai',
            name='siuntinio_plotis',
        ),
        migrations.RemoveField(
            model_name='siuntiniai',
            name='siuntinio_svoris',
        ),
    ]
