# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0006_auto_20170518_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miestai',
            name='salis',
        ),
        migrations.RemoveField(
            model_name='siuntiniai',
            name='siuntinio_salis',
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_tikslo_miestas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Miestai2', to='pagrindinis.Miestai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_tikslo_salis',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Salys2', to='pagrindinis.Salys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_vietos_miestas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Miestai1', to='pagrindinis.Miestai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_vietos_salis',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Salys1', to='pagrindinis.Salys'),
            preserve_default=False,
        ),
    ]
