# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0007_auto_20170518_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siuntiniai',
            name='siuntinio_tikslo_salis',
        ),
        migrations.RemoveField(
            model_name='siuntiniai',
            name='siuntinio_vietos_salis',
        ),
        migrations.AddField(
            model_name='miestai',
            name='salis',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pagrindinis.Salys'),
            preserve_default=False,
        ),
    ]
