# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0009_miestai_salis_miestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miestai',
            name='salis_miestas',
            field=models.CharField(default='', max_length=200),
        ),
    ]
