# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0012_auto_20170520_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siuntiniai',
            name='siuntejas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
