# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0017_siuntiniai_surinkimo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siuntiniai',
            name='siuntinio_apibudinimas',
            field=models.CharField(max_length=50),
        ),
    ]
