# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0018_auto_20170522_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='vezejas',
            name='telefono_numeris',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
