# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0021_remove_siuntiniai_siuntinio_miestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siuntiniai',
            name='gavejo_telefonas',
            field=models.CharField(default='541461564', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_tikslo_gatve',
            field=models.CharField(default='545646545', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_tikslo_namas',
            field=models.CharField(default='5646464', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_tikslo_pastokodas',
            field=models.CharField(default=1245, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_vietos_gatve',
            field=models.CharField(default='d4d5d4', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_vietos_namas',
            field=models.CharField(default='dsdsds', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siuntiniai',
            name='siuntinio_vietos_pastokodas',
            field=models.CharField(default='dsdfsd', max_length=20),
            preserve_default=False,
        ),
    ]
