# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagrindinis', '0023_auto_20170525_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='vezejas',
            name='vezejas_main_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siuntejas',
            name='siuntejas_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siuntiniai',
            name='vezejas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vezejas', to=settings.AUTH_USER_MODEL),
        ),
    ]
