# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagrindinis', '0024_auto_20170525_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siuntiniai',
            name='vezejas',
        ),
    ]
